apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-script
  namespace: k6
data:
  script.js: |
    import http from 'k6/http';
    import { sleep } from 'k6';

    export let options = {
      vus: 5,
      duration: '30s',
    };

    export default function () {
      http.get('https://test.k6.io');
      sleep(1);
    }
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: k6-test-cron
  namespace: k6
spec:
  schedule: "*/1 * * * *"  # every 10 minutes
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3600  # auto-delete finished Job after 1 hour
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: kubectl
            image: bitnami/kubectl:latest
            command:
            - /bin/sh
            - -c
            - |
              cat <<'EOF' | kubectl apply -f -
              apiVersion: k6.io/v1alpha1
              kind: K6
              metadata:
                generateName: simple-k6-test-
                namespace: k6
              spec:
                parallelism: 2
                script:
                  configMap:
                    name: k6-script
                    file: script.js
              EOF
