apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-script
  namespace: k6
data:
  script.js: |
    import http from 'k6/http';
    import { sleep } from 'k6';

    export let options = {
      vus: 5,
      duration: '30s',
    };

    export default function () {
      http.get('https://test.k6.io');
      sleep(1);
    }
---
apiVersion: k6.io/v1alpha1
kind: K6
metadata:
  name: simple-k6-test
  namespace: k6
spec:
  parallelism: 1
  script:
    configMap:
      name: k6-script
      file: script.js
